⬆️ Update to 1.20.4
- Fully migrate to NeoForge
- Support for 1.20.2 and 1.20.3
- Drop support for 1.20.1 in this branch
- Support different `mods.toml` versions
- Fail fast in `forEachVersion` scripts

diff --git a/forEachVersion b/forEachVersion
--- a/forEachVersion
+++ b/forEachVersion
@@ -10,6 +10,7 @@ getProperty()
 runForVersion()
 {
   ./gradlew $2 -PmcVersion=$1
+  return $?
 }
 
 mcVersions=$(getProperty "mcVersions")
@@ -26,5 +27,11 @@ for mcVersion in "${versionArray[@]}"
 do
   echo "Building for Minecraft $mcVersion"
   runForVersion $mcVersion "$gradleCommand"
+  if [ $? -ne 0 ]; then
+    echo
+    echo "Build failed for Minecraft $mcVersion"
+    echo "  Aborted remaining builds."
+    exit 1
+  fi
   echo
 done
